app/mod_adm/models.py
# -*- coding:utf-8 -*- 
from flask_login import UserMixin
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

# On créé notre modèle User


class Meal(db.Document):
	name = db.StringField(default='')

	def __str__(self):
		return self.name


class User(db.Document, UserMixin):
	email = db.StringField()
	password = db.StringField()
	meals = db.ListField(db.ReferenceField(Meal))

	def set_password(self, password):
		self.password = generate_password_hash(password)

	def check_password(self, passwd):
		return check_password_hash(self.password, passwd)

app/mod_adm/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import Required, Email


class LoginForm(Form):
	email = TextField('', [Email(), Required(
		message='Forgot your email address?')], default="my@fra.com",
	)
	password = PasswordField('', [Required(
		message='Must provide a password. ;-)')], default="fra", render_kw={"placeholder": "Password"}
	)

app/__init__.py
# Import flask and template operators
from flask import Flask, render_template
from flask_mongoengine import MongoEngine
from flask_admin import Admin
from flask_login import LoginManager

app = Flask(__name__)

# Config
app.config.from_object('config')

# Database init
db = MongoEngine(app)

# Login Management
login_manager = LoginManager()
login_manager.login_view = "/admin/login/"
login_manager.init_app(app)


@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

# Import a module / component using its blueprint handler variable (mod_auth)
from app.mod_adm.views import mod_adm as adm_module
from app.mod_adm.views import AdminCustomView, UserView, MealView
from app.mod_adm.models import User, Meal

# Register blueprint(s)
app.register_blueprint(adm_module, url_prefix='/admin')
admin = Admin(name='Admin', template_mode='bootstrap3', index_view=AdminCustomView())
admin.add_view(MealView(Meal))
admin.add_view(UserView(User))
admin.init_app(app)

app/mod_adm/views.py
# -*- coding:utf-8 -*-
# Import flask dependencies
from flask import (
    Blueprint, request, render_template,
    flash, redirect
)

# Import module forms
from app.mod_adm.forms import LoginForm

# Import module models (i.e. User)
from app.mod_adm.models import User

from flask_admin.base import AdminIndexView, expose
from flask_admin.contrib.mongoengine import ModelView
from mongoengine.queryset import DoesNotExist

from flask_login import (
    current_user, login_required,
    login_user, logout_user
)

from app import login_manager
# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_adm = Blueprint('adm', __name__, url_prefix='/admin')


@login_manager.user_loader
def load_user(user_id):
    if user_id:
        return User.objects.get(id=user_id)

# Set the route and accepted methods
@mod_adm.route('/login/', methods=['GET', 'POST'])
def login():
    next = "/admin"
    # If sign in form is submitted
    form = LoginForm(request.form)

    # Verify the sign in form
    if form.validate():

        # Create an user if not users found
        if len(User.objects) == 0:
            user = User(email=form.email.data)
            user.set_password(form.password.data)
            user.save()
        else:
            try:
                user = User.objects.get(
                    email=form.email.data,
                )
            except DoesNotExist:
                user = None
                form['email'].errors.append('Email not found')
                form['password'].errors.append('Password incorrect')

            if user is not None:
                if user.check_password(form.password.data):
                    login_user(user)

                return redirect(next)

            else:
                flash('Wrong email or password', 'error-message')

    else:
        next = request.args.get('next')

    return render_template("adm/login.html", form=form, next=next)


@mod_adm.route("/logout/", methods=["GET"])
@login_required
def logout():
    logout_user()
    flash(u'Vous êtes maintenant déconnecté', 'success')
    return redirect("/admin/login/")


class AdminCustomView(AdminIndexView):

    @expose('/')
    def index(self):
            return self.render('adm/index.html')

    def _handle_view(self, name, **kwargs):

        if not self.is_accessible():
            return redirect('/admin/login/')
        else:
            print("OK")

    def is_accessible(self):
        rep = False
        if current_user.is_authenticated:
            rep = True
        return rep


class MealView(ModelView):
    column_filters = ['name']
    column_searchable_list = ('name',)


class UserView(ModelView):
    column_filters = ['email']
    column_searchable_list = ('email', 'password')

app/templates/adm/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Connexion utilisateur</title>
	<!-- Latest compiled and minified CSS -->
	<link 
		rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
		integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">

	<script
		src="https://code.jquery.com/jquery-3.1.0.min.js" 
		integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous">
	</script>
	<!-- Latest compiled and minified JavaScript -->
	<script 
		src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
		integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
	</script>

	<script 
		src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
		integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
	</script>
</head>
<body>
	<div class="container">
		{% block page_cont %}
		{% endblock %}
	</div>
</body>
</html>

app/templates/adm/formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    {% for error in field.errors %}
     <div class="alert alert-danger">
        <p><strong>Error!</strong> {{error}}</p>
    </div>
    {% endfor %}
  {% endif %}
  </dd>
{% endmacro %}

app/templates/adm/index.html
{% extends 'admin/master.html' %}

{% block access_control %}
	<ul class="nav navbar-nav navbar-right">
		<li><a href="{{ url_for('adm.logout') }}">Logout</a></li>
	</ul>
{% endblock %}
	
{% block body %}
  <h2>Bienvenue dans Flask-admin</h2>
{% endblock %}

app/templates/adm/login.html
{% extends "adm/base.html" %}

{% block page_cont %}

{% from "adm/formhelpers.html" import render_field %}

<div class="row">
	<div class="col-md-push-3 col-md-6">
	<form method="post" action="{{ url_for('adm.login', next=next) }}">
	  <dl>
	    {{ render_field(form.email) }}
	    {{ render_field(form.password) }}
	    {{form.hidden_tag()}}
	  </dl>
	  <p><input type="submit" value="Connexion">
	</form>
	</div>
</div>

{% endblock %}